[build]
    command = "next build"
    base = "."
    publish = ".next"

[build.environment]
    NEXT_USE_NETLIFY_EDGE = "true"

[functions]
    directory = "my_functions"

[[plugins]]
    package = "@netlify/plugin-nextjs"